-- ============================================================================
-- ⚠️ FICHIER NEUTRALISÉ — NE PLUS EXÉCUTER.
--
-- Ce fichier redéfinissait handle_new_user() SANS l'allowlist « inscription sur
-- invitation » (H2). Le relancer DÉSACTIVERAIT silencieusement H2.
--
-- La version canonique et sécurisée de handle_new_user() vit désormais dans :
--        supabase/access-control.sql
-- Elle gère DÉJÀ la récupération du nom et de la photo depuis Google/LinkedIn
-- (via raw_user_meta_data → full_name / name / avatar_url / picture), donc il
-- n'y a rien à exécuter ici.
-- ============================================================================
